# Generated by Django 4.0.2 on 2022-02-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equiposmodel',
            name='caducidad',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fecha de caducidad de la Póliza'),
        ),
        migrations.AddField(
            model_name='equiposmodel',
            name='duracion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Duración de la Póliza'),
        ),
        migrations.AlterField(
            model_name='equiposmodel',
            name='serie',
            field=models.CharField(max_length=80, verbose_name='Número de Serie'),
        ),
    ]
