# Generated by Django 4.0.2 on 2022-02-22 17:55

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0005_remove_equiposmodel_imagen2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equiposmodel',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
